replace conda with a native python, fix numpy/matplotlib

diff --git a/Dockerfile.sandbox b/Dockerfile.sandbox
--- a/Dockerfile.sandbox
+++ b/Dockerfile.sandbox
@@ -58,32 +58,77 @@ RUN pipenv install --deploy --system
 # This must come after the first pipenv command! From the docs:
 # All RUN instructions following an ARG instruction use the ARG variable
 # implicitly (as an environment variable), thus can cause a cache miss.
-ARG DEV
+
+# TODO: refactor this, I don't like that pytest depends on a docker
+# container
+
+# ARG DEV
 
 # Install numpy when in dev mode; one of the unit tests needs it.
-RUN if [ -n "${DEV}" ]; \
-    then \
-        pipenv install --deploy --system --dev \
-        && PYTHONUSERBASE=/opt/python/user_base pip install numpy~=1.19; \
-    fi
-
-# At the end to avoid re-installing dependencies when only a config changes.
-# It's in the venv image because the final image is not used during development.
-# COPY diggy-sandbox/config/ /sandbox/config
+# RUN if [ -n "${DEV}" ]; \
+#     then \
+#         pipenv install --deploy --system --dev \
+#         && PYTHONUSERBASE=/opt/python/diggy pip install numpy~=1.20; \
+#     fi
 
 # ------------------------------------------------------------------------------
 FROM venv as sandbox
 
-# Install all additional languages here
+# Install all additional dependencies here
 RUN apt-get -y update \
     && apt-get install -y \
         curl \
         gnupg2 \
         procps \
+        # Conda dependencies, see below
+        # bzip2 \
+        # ca-certificates \
+        # libglib2.0-0 \
+        # libsm6 \
+        # libxext6 \
+        # libxrender1 \
+        # mercurial \
+        # subversion \
+        # wget \
     && rm -rf /var/lib/apt/lists/*
 
 # == Python
-# Nothing to do here, I am using python:slim-buster already
+
+# NOTE: I could not make conda work with nsjail, i.e. numpy fails with
+# this error: Intel MKL FATAL ERROR: Cannot load <mkl-loader>. I am
+# stuck, and if you manage to get it up and running, please let me
+# know.
+
+# ARG CONDA_VERSION=py38_4.9.2
+# ARG CONDA_MD5=122c8c9beb51e124ab32a0fa6426c656
+
+# ENV PATH /opt/conda/bin:$PATH
+
+# # Based on https://github.com/ContinuumIO/docker-images
+# RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh -O miniconda.sh && \
+#     echo "${CONDA_MD5}  miniconda.sh" > miniconda.md5 && \
+#     if ! md5sum --status -c miniconda.md5; then exit 1; fi && \
+#     mkdir -p /opt && \
+#     sh miniconda.sh -b -p /opt/conda && \
+#     rm miniconda.sh miniconda.md5 && \
+#     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
+#     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
+#     echo "conda activate base" >> ~/.bashrc && \
+#     find /opt/conda/ -follow -type f -name '*.a' -delete && \
+#     find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
+#     /opt/conda/bin/conda clean -afy
+# RUN conda config --add channels intel
+# RUN conda create --name diggy intelpython3_core python=3.7
+
+# Pre-install Python packages
+
+# SHELL ["conda", "run", "-n", "diggy", "/bin/bash", "-c"]
+
+# RUN yes | conda install numpy \
+#     matplotlib
+
+RUN PYTHONUSERBASE=/opt/python/diggy pip install matplotlib \
+  numpy
 
 # == Ruby
 # Based on https://github.com/ms-ati/docker-rvm/blob/master/Dockerfile
@@ -130,5 +175,8 @@ FROM sandbox
 WORKDIR /sandbox
 COPY diggy-sandbox /sandbox
 ADD diggy-sandbox/docker/web.conf /etc/supervisor/conf.d/
+
+# Activate virtual envs like rvm
+SHELL ["/bin/bash", "--login", "-c"]
 
 ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
